version: '3.8'

services:
  mysql:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: withins_db
    restart: always
    ports:
      - "3305:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/config/my.cnf:/etc/mysql/conf.d/custom.cnf
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: withins
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local